/**
 * UI strings. `increase`, `decrease` and `reset` may contain `{label}` to place the
 * setting name (e.g. "Increase {label}"); without it the name is appended.
 */
export const defaultLabels = Object.freeze({
  launcher: "Accessibility settings",
  activeAdjustments: "Adjustments are on",
  title: "Accessibility",
  close: "Close accessibility settings",
  language: "Language",
  skipToContent: "Skip to main content",
  resetAll: "Reset all",
  resetDone: "All accessibility settings have been reset",
  statement: "Accessibility statement",
  hideWidget: "Hide widget",
  widgetHidden: "Accessibility button hidden. Press {shortcut} to bring it back.",
  activeCount: "{n} on",

  profilesTitle: "Quick profiles",
  seizureSafe: "Motion sensitivity",
  seizureSafeDesc: "Stops animations and softens colors",
  visionImpaired: "Low vision",
  visionImpairedDesc: "Larger text, clearer font, more contrast",
  adhdFriendly: "Focus mode",
  adhdFriendlyDesc: "Dims the page around what you read",
  cognitiveDisability: "Easy reading",
  cognitiveDisabilityDesc: "Marks headings and links, adds a reading line",
  keyboardNav: "Keyboard user",
  keyboardNavDesc: "Strong outline on the focused control",
  screenReader: "Quiet media",
  screenReaderDesc: "Mutes media that starts playing on its own",
  olderAdults: "Comfortable reading",
  olderAdultsDesc: "Bigger text, more spacing, large cursor",

  textSection: "Text",
  contentScale: "Page zoom",
  fontSize: "Text size",
  lineHeight: "Line spacing",
  letterSpacing: "Letter spacing",
  increase: "Increase",
  decrease: "Decrease",
  reset: "Reset",
  textAlign: "Alignment",
  alignDefault: "Auto",
  alignLeft: "Left",
  alignCenter: "Center",
  alignRight: "Right",
  alignJustify: "Justify",
  readableFont: "Readable font",

  colorSection: "Color",
  contrast: "Contrast",
  contrastOff: "Off",
  darkContrast: "Dark",
  lightContrast: "Light",
  highContrast: "High",
  saturation: "Saturation",
  saturationOff: "Off",
  monochrome: "Gray",
  lowSaturation: "Low",
  highSaturation: "High",
  textColor: "Text color",
  titleColor: "Heading color",
  backgroundColor: "Background color",

  readingSection: "Reading aids",
  highlightTitles: "Highlight headings",
  highlightLinks: "Highlight links",
  textMagnifier: "Text magnifier",
  readingGuide: "Reading line",
  readingMask: "Focus window",
  readMode: "Open read mode",
  readModeTitle: "Read mode",
  closeReadMode: "Close read mode",
  noReadableContent: "No readable content was found on this page.",
  image: "Image",

  motionSection: "Motion & navigation",
  stopAnimations: "Stop animations",
  muteSounds: "Mute media",
  hideImages: "Hide images",
  highlightFocus: "Highlight focus",
  highlightHover: "Highlight on hover",
  cursor: "Cursor",
  cursorDefault: "Default",
  cursorBlack: "Large dark",
  cursorWhite: "Large light",
});

export type AccessibilityLabels = { [K in keyof typeof defaultLabels]: string };

export const arabicLabels: AccessibilityLabels = Object.freeze({
  launcher: "إعدادات إمكانية الوصول",
  activeAdjustments: "توجد تعديلات مفعّلة",
  title: "إمكانية الوصول",
  close: "إغلاق إعدادات إمكانية الوصول",
  language: "اللغة",
  skipToContent: "تخطَّ إلى المحتوى الرئيسي",
  resetAll: "إعادة ضبط الكل",
  resetDone: "تمت إعادة ضبط جميع إعدادات إمكانية الوصول",
  statement: "بيان إمكانية الوصول",
  hideWidget: "إخفاء الأداة",
  widgetHidden: "تم إخفاء زر إمكانية الوصول. اضغط {shortcut} لإظهاره مرة أخرى.",
  activeCount: "{n} مفعّل",

  profilesTitle: "ملفات سريعة",
  seizureSafe: "الحساسية للحركة",
  seizureSafeDesc: "يوقف الحركة ويخفف الألوان",
  visionImpaired: "ضعف البصر",
  visionImpairedDesc: "نص أكبر وخط أوضح وتباين أعلى",
  adhdFriendly: "وضع التركيز",
  adhdFriendlyDesc: "يعتّم الصفحة حول ما تقرأه",
  cognitiveDisability: "قراءة أسهل",
  cognitiveDisabilityDesc: "يميّز العناوين والروابط ويضيف خط قراءة",
  keyboardNav: "مستخدم لوحة المفاتيح",
  keyboardNavDesc: "إطار واضح حول العنصر المحدد",
  screenReader: "وسائط هادئة",
  screenReaderDesc: "يكتم الوسائط التي تبدأ التشغيل تلقائيًا",
  olderAdults: "قراءة مريحة",
  olderAdultsDesc: "نص أكبر ومسافات أوسع ومؤشر كبير",

  textSection: "النص",
  contentScale: "تكبير الصفحة",
  fontSize: "حجم النص",
  lineHeight: "تباعد الأسطر",
  letterSpacing: "تباعد الأحرف",
  increase: "زيادة",
  decrease: "تقليل",
  reset: "إعادة ضبط",
  textAlign: "المحاذاة",
  alignDefault: "تلقائي",
  alignLeft: "يسار",
  alignCenter: "وسط",
  alignRight: "يمين",
  alignJustify: "ضبط",
  readableFont: "خط سهل القراءة",

  colorSection: "الألوان",
  contrast: "التباين",
  contrastOff: "إيقاف",
  darkContrast: "داكن",
  lightContrast: "فاتح",
  highContrast: "عالٍ",
  saturation: "التشبع",
  saturationOff: "إيقاف",
  monochrome: "رمادي",
  lowSaturation: "منخفض",
  highSaturation: "مرتفع",
  textColor: "لون النص",
  titleColor: "لون العناوين",
  backgroundColor: "لون الخلفية",

  readingSection: "أدوات القراءة",
  highlightTitles: "تمييز العناوين",
  highlightLinks: "تمييز الروابط",
  textMagnifier: "مكبّر النص",
  readingGuide: "خط القراءة",
  readingMask: "نافذة التركيز",
  readMode: "فتح وضع القراءة",
  readModeTitle: "وضع القراءة",
  closeReadMode: "إغلاق وضع القراءة",
  noReadableContent: "لم يتم العثور على محتوى قابل للقراءة في هذه الصفحة.",
  image: "صورة",

  motionSection: "الحركة والتنقل",
  stopAnimations: "إيقاف الحركة",
  muteSounds: "كتم الوسائط",
  hideImages: "إخفاء الصور",
  highlightFocus: "تمييز التركيز",
  highlightHover: "تمييز عند التمرير",
  cursor: "المؤشر",
  cursorDefault: "افتراضي",
  cursorBlack: "كبير داكن",
  cursorWhite: "كبير فاتح",
});

export interface AccessibilityLanguage {
  /** BCP-47 code, matched against <html lang> to pick the initial language. */
  code: string;
  /** Name shown in the language menu, in its own language. */
  name: string;
  labels: Partial<AccessibilityLabels>;
  dir?: "ltr" | "rtl";
}

export const builtInLanguages: AccessibilityLanguage[] = Object.freeze([
  Object.freeze({ code: "en", name: "English", labels: defaultLabels, dir: "ltr" as const }),
  Object.freeze({ code: "ar", name: "العربية", labels: arabicLabels, dir: "rtl" as const }),
]) as AccessibilityLanguage[];
